# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET with blazor

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/azFunction
    - name: Build
      run: dotnet build src/azFunction --configuration Release --no-restore --output ./output

    - name: Deploy to GitHub Pages
    #  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/wwwroot
          publish_branch: master
