name: dotnet using calling

on:
  workflow_dispatch:

jobs:

  # build:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnetbuild.yml@master

  # test:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnettest.yml@master
    
  # run:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnetrun.yml@master
  #   with:
  #     FILENAME: Program.csproj


  all:
    uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnet.yml@master
    with:
      path1: src/azFunction
      configuration: Release
