name: dotnet using calling

on:
  workflow_dispatch:
   inputs: 
    path1: 
      description: 'The version of .NET to install' 
      required: true
      default: 'src/azFunction'
      type: string  

jobs:

  # build:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnetbuild.yml@master

  # test:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnettest.yml@master
    
  # run:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnetrun.yml@master
  #   with:
  #     FILENAME: Program.csproj

  all:
    uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnet.yml@master
    with:
      path1: ${{ github.event.inputs.path1 }}
