name: Docker Login and Pull Image

on:
  push:
    branches:
      - master  # Adjust this to your target branch

jobs:
  docker-login-and-pull:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Login to Docker
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry:  "https://login.docker.com/u/login"       # e.g., 'your.registry.com'
          username: "anusha414"            # e.g., 'your_username'
          password: "Anusha414"             # e.g., 'your_password'

      # Step 3: Pull the Docker image
      - name: Pull Docker Image
        run: |
          docker pull ubuntu:latest   # Replace with your image and tag
