name: Generate Swagger

on:
  push:
    branches:
      - master # Change this to your default branch if needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0' # Specify your target .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish

      - name: Generate Swagger file
        run: |
          dotnet tool install --global dotnet-swagger
          dotnet swagger tofile --output swagger.json ./publish/Program.dll v1
        env:
          DOTNET_CLI_HOME: /tmp # Required for installing global tools

      - name: Upload Swagger file
        uses: actions/upload-artifact@v2
        with:
          name: swagger-json
          path: swagger.json
