name: Generate Swagger

on:
  push:
    branches:
      - master # Change this to your default branch if needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0' # Specify your target .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish

      - name: Generate Swagger file
        run: |
          # Start the application in the background
          dotnet ./publish/Program.dll &
          sleep 10 # Wait for the application to start

          # Fetch the Swagger JSON
          curl -o swagger.json http://localhost:5000/swagger/v1/swagger.json

      # - name: Upload Swagger file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: swagger-json
      #     path: swagger.json
